
'use server';
/**
 * @fileOverview An AI flow to generate information about a musical artist and album.
 *
 * - generateRecordInfo - A function that generates artist and album bios.
 * - GenerateRecordInfoInput - The input type for the function.
 * - GenerateRecordInfoOutput - The return type for the function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateRecordInfoInputSchema = z.object({
  artist: z.string().describe('The name of the musical artist.'),
  title: z.string().describe('The title of the album.'),
  year: z.number().optional().describe('The release year of the album.'),
  distributorId: z.string().optional().describe('The ID of the distributor making the request.'),
});
export type GenerateRecordInfoInput = z.infer<typeof GenerateRecordInfoInputSchema>;

// The output schema now only contains the text generated by the AI.
// The tracklist is handled separately by the client.
const GenerateRecordInfoOutputSchema = z.object({
  artistBio: z.string().describe('A concise biography of the artist, including their date of birth (d.o.b.), city of birth, and an often unknown fun fact. Write in an engaging, narrative style. Aim for 2-3 paragraphs.'),
  albumInfo: z.string().describe('A brief but insightful overview of the album, including its release date, sales figures, significance, musical style, and reception. Aim for 2-3 paragraphs.'),
});
export type GenerateRecordInfoOutput = z.infer<typeof GenerateRecordInfoOutputSchema>;


export async function generateRecordInfo(input: GenerateRecordInfoInput): Promise<GenerateRecordInfoOutput> {
  return generateRecordInfoFlow(input);
}


const prompt = ai.definePrompt({
  name: 'generateRecordInfoPrompt',
  input: {schema: GenerateRecordInfoInputSchema},
  // The prompt's output schema is now the same as the flow's output schema.
  output: {schema: GenerateRecordInfoOutputSchema},
  prompt: `You are a passionate music journalist and historian. Given an artist, album title, and release year, generate the following information.

Your tone should be engaging and informative, like something you'd read in a respected music magazine.

Artist: {{{artist}}}
Album: {{{title}}}
{{#if year}}
Album Release Year: {{{year}}}
{{/if}}

Based on this, provide:
1.  A concise artist biography with d.o.b. city of birth, and if possible an often unknown fun fact.
2.  A brief but insightful overview of the album and the date of release and sales.
`,
});

const generateRecordInfoFlow = ai.defineFlow(
  {
    name: 'generateRecordInfoFlow',
    inputSchema: GenerateRecordInfoInputSchema,
    outputSchema: GenerateRecordInfoOutputSchema,
  },
  async (input) => {
    const {output} = await prompt(input);
    if (!output) {
      throw new Error("Failed to get a response from the language model.");
    }
    return output;
  }
);
